#!/bin/csh -f
#
# Kills the running server, rotates the logs, restarts the server
 
cd /home/rkinney/VASSALserver/serverlogs

killall -s SIGKILL /usr/java/jdk1.6.0_13/jre
#killall -s SIGKILL /usr/lib/jvm/jre
setenv date `date`
cp serverLog "serverLog.${date}"
gzip "serverLog.${date}"
sleep 5 
cd ..
./startServer
