#!/bin/csh -f
#
# Kills the running server, rotates the logs, restarts the server
 
cd /home/vserver/server/log

killall -s SIGKILL /usr/bin/java
setenv date `date +%Y%m%d-%H%M%S`
cp vassal-server "vassal-server.${date}"
gzip "vassal-server.${date}"
sleep 5 
cd ..
./startServer
