#!/bin/sh

/usr/bin/java -Djava.util.logging.config.file=logging.properties -cp Vengine.jar -Xmx512M VASSAL.chat.node.Server -port 5050 -URL http://www.vassalengine.org/util/ >& ./log/vassal-server &
echo $! > pid

